kind: Deployment
apiVersion: apps/v1
metadata:
  name: superduper-canary
spec:
  replicas: 2
  selector:
    matchLabels:
      app: superduper
  template:
    metadata:
      name: superduper
      labels:
        app: superduper
        env: canary
    spec:
      containers:
      - name: superduper
        image: myk8clusterreg001.azurecr.io/superduper:v0.0.1
        ports:
        - containerPort: 4000
      imagePullSecrets:
      - name: dupa1-auth

