kind: Deployment
apiVersion: apps/v1
metadata:
  name: whoami
spec:
  replicas: 1
  selector:
    matchLabels:
      app: whoami
  template:
    metadata:
      name: whoami
      labels:
        app: whoami
        env: dev
    spec:
      containers:
      - name: whoami
        image: acrdemo77.azurecr.io/whoami:v1
        ports:
        - containerPort: 4000
      imagePullSecrets:
      - name: dupa1-auth
---
kind: Service
apiVersion: v1
metadata:
  name: whoami
  labels:
    name: whoami
spec:
  type: ClusterIP
  ports:
  - port: 80
    targetPort: 4000
  selector:
    app: whoami
