apiVersion: apps/v1
kind: Deployment
metadata:
  name: superduper
spec:
  replicas: 1
  selector:
    matchLabels:
      app: superduper
  template:
    metadata:
      labels:
        app: superduper
        env: prod
    spec:
      containers:
      - name: dupa1
        image: myk8clusterreg001.azurecr.io/superduper:v0.0.1
        ports:
        - containerPort: 4000
      imagePullSecrets:
        - name: dupa1-auth
---
apiVersion: v1
kind: Service
metadata: 
  name: superduper
spec:
  type: LoadBalancer
  ports:
  - port: 80
    targetPort: 4000
  selector:
    app: superduper
