kind: Deployment
apiVersion: apps/v1
metadata:
  name: k8s_web
spec:
  replicas: 2
  selector:
    matchLabels:
      app: k8s_web
  template:
    metadata:
      name: k8s_web
      labels:
        app: k8s_web
        env: prod
    spec:
      containers:
      - name: k8s_web
        image: wtf123.azurecr.io/k8s_web:v1
        ports:
        - containerPort: 4000
      imagePullSecrets:
      - name: dupa1-auth

