kind: Deployment
apiVersion: apps/v1
metadata:
  name: superduper
spec:
  replicas: 2
  selector:
    matchLabels:
      app: superduper
  template:
    metadata:
      name: superduper
      labels:
        app: superduper
        env: prod
    spec:
      containers:
      - name: superduper
        image: myk8clusterreg001.azurecr.io/superduper:v0.0.1
        ports:
        - containerPort: 4000
      imagePullSecrets:
      - name: dupa1-auth
---
kind: Service
apiVersion: v1
metadata:
  name: superduper
  labels:
    name: superduper
spec:
  type: LoadBalancer
  ports:
  - port: 80
    targetPort: 4000
  selector:
    app: superduper
